"""Add soft delete to org unit

Revision ID: 127b0e8a70e8
Revises: 088c0e55428e
Create Date: 2026-08-15 03:05:20.954683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127b0e8a70e8'
down_revision: Union[str, Sequence[str], None] = '088c0e55428e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizational_units', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('organizational_units', sa.Column('deletion_status', sa.String(length=50), server_default=sa.text("'NONE'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizational_units', 'deletion_status')
    op.drop_column('organizational_units', 'is_deleted')
    # ### end Alembic commands ###
