"""Add s3_prefix and ingestion_jobs

Revision ID: 2e0a7c3e8e64
Revises: d324f5021abb
Create Date: 2026-08-12 16:04:51.587024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0a7c3e8e64'
down_revision: Union[str, Sequence[str], None] = 'd324f5021abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('PARSE', 'QUALITY', 'AST', 'FORMULA', 'QUESTION', 'ENTITY', 'RELATION', 'CHUNK', 'EMBED', 'GRAPH', 'MANIFEST', name='ingestionstage'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='ingestionjobstatus'), nullable=False),
    sa.Column('input_s3_key', sa.Text(), nullable=True),
    sa.Column('output_s3_key', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('s3_prefix', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('original_s3_key', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('manifest_s3_key', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('parser_used', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('parser_version', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('processing_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_version')
    op.drop_column('documents', 'quality_score')
    op.drop_column('documents', 'parser_version')
    op.drop_column('documents', 'parser_used')
    op.drop_column('documents', 'manifest_s3_key')
    op.drop_column('documents', 'original_s3_key')
    op.drop_column('documents', 's3_prefix')
    op.drop_table('ingestion_jobs')
    # ### end Alembic commands ###
