"""Add AnalysisJob model

Revision ID: 79acb8a52afc
Revises: 5e6d77c02560
Create Date: 2026-08-12 17:10:53.701625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79acb8a52afc'
down_revision: Union[str, Sequence[str], None] = '5e6d77c02560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_type', sa.Enum('SUMMARIZE', 'QUIZ', 'FORMULA_REVISION', 'PYQ_MAPPING', 'COURSE_SUMMARY', 'DOCUMENT_COMPARISON', name='analysistype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='analysisjobstatus'), nullable=False),
    sa.Column('input_metadata', sa.JSON(), nullable=True),
    sa.Column('result_s3_key', sa.Text(), nullable=True),
    sa.Column('result_md_s3_key', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
