"""Remove CoursePermission

Revision ID: 8e25ed7368dd
Revises: bae758c9718f
Create Date: 2026-06-18 00:32:46.423835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e25ed7368dd'
down_revision: Union[str, Sequence[str], None] = 'bae758c9718f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_permissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_offering_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('can_publish', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('can_edit_faculty', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], name=op.f('course_permissions_course_offering_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('course_permissions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('course_permissions_pkey')),
    sa.UniqueConstraint('user_id', 'course_offering_id', name=op.f('course_permissions_user_id_course_offering_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
