"""s3_key_and_prerequisites

Revision ID: af1a58b04c48
Revises: c839304e47e3
Create Date: 2026-06-18 15:56:40.205933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1a58b04c48'
down_revision: Union[str, Sequence[str], None] = 'c839304e47e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_prerequisites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('prerequisite_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'prerequisite_id')
    )
    op.add_column('documents', sa.Column('s3_key', sa.Text(), nullable=False))
    op.drop_column('documents', 's3_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('s3_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('documents', 's3_key')
    op.drop_table('course_prerequisites')
    # ### end Alembic commands ###
