"""Add soft delete and cleanup jobs

Revision ID: c839304e47e3
Revises: 8e25ed7368dd
Create Date: 2026-06-18 02:39:45.008229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c839304e47e3'
down_revision: Union[str, Sequence[str], None] = '8e25ed7368dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleanup_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('courses', sa.Column('deletion_status', sa.String(length=50), nullable=False, server_default='NONE'))
    op.alter_column('courses', 'credits',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('documents', sa.Column('parsing_instructions', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('version', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('documents', sa.Column('deletion_status', sa.String(length=50), nullable=False, server_default='NONE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'deletion_status')
    op.drop_column('documents', 'is_deleted')
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'parsing_instructions')
    op.alter_column('courses', 'credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('courses', 'deletion_status')
    op.drop_column('courses', 'is_deleted')
    op.drop_table('cleanup_jobs')
    # ### end Alembic commands ###
