"""Add summary and keywords to conversation

Revision ID: d324f5021abb
Revises: 07b2dbc8c71c
Create Date: 2026-08-04 02:02:39.434304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd324f5021abb'
down_revision: Union[str, Sequence[str], None] = '07b2dbc8c71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'keywords')
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
