"""Add course_code and academic_year to Content

Revision ID: fd39509ae729
Revises: 62754701f00a
Create Date: 2026-06-09 15:39:20.702045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd39509ae729'
down_revision: Union[str, Sequence[str], None] = '62754701f00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('course_code', sa.String(), nullable=False))
    op.add_column('content', sa.Column('academic_year', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'academic_year')
    op.drop_column('content', 'course_code')
    # ### end Alembic commands ###
